version: "3.9"

services:
  
  redis:
    image: "redis:alpine"
    container_name: redis
    restart: always

  biosim:
    build: ./BioSim/
    container_name : biosim
    # command: python manage.py runserver 0.0.0.0:8000
    command: gunicorn BioSim.asgi:application -c gunicorn_config.py
    volumes:
      # - ./vol/static:/app/BioSim/static
      # - ./vol/app/migrations:/app/app/migrations
      - ./BioSim:/app/
    ports:
      - 8000:8000
    depends_on:
      - redis
    restart: always
    environment:
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - DJANGO_ALLOWED_HOSTS=${DOMAIN}
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/0

  celery:
    build: ./BioSim/
    container_name: celery
    command: ./start_celery.sh
    # volumes:
    #   - ./vol:/usr/src/app
    #   - ./vol/app/logs/:/app/app/logs/
    volumes:
      - ./vol/plots:/app/plots/
    environment:
      - DEBUG=1
      - DJANGO_ALLOWED_HOSTS=${DOMAIN}
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/0
    depends_on:
      - biosim
      - redis
